{
 "title": "Disk Read Rate",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cpu) (rate(node_cpu_seconds_total{mode=~\"user|system\"}[1m]))",
     "legendFormat": "{{cpu}}"
    },
    {
     "expr": "sum(sum by (cpu) (rate(node_cpu_seconds_total{mode=~\"user|system\"}[1m])))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "Memory Used"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Installed Memory" },
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "Swapped"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available Disk Storage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (device) (node_filesystem_free_bytes / node_filesystem_size_bytes)*100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Read Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}